/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calcularnota;

/**
 *Nesse trabalho a calculadora foi feita
 * com a ajuda de vídeos encontrados
 * na internet,e com o que foi
 * aprendido nas aulas
 * 
 * 
 */
public class janelafrontal extends javax.swing.JFrame {

    /**
     * Creates new form janelafrontal
     */
    public janelafrontal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primeironumero = new javax.swing.JTextField();
        segundonumero = new javax.swing.JTextField();
        result = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        primeironumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeironumeroActionPerformed(evt);
            }
        });
        getContentPane().add(primeironumero);
        primeironumero.setBounds(30, 52, 80, 50);
        getContentPane().add(segundonumero);
        segundonumero.setBounds(130, 52, 90, 50);
        getContentPane().add(result);
        result.setBounds(290, 50, 90, 50);

        jLabel1.setText("=");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 60, 30, 30);

        jButton1.setText("+");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 160, 80, 50);

        jButton2.setText("-");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 160, 90, 50);

        jButton3.setText("/");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 230, 80, 50);

        jButton4.setText("*");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton4MouseReleased(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(130, 230, 90, 50);
        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(230, 170, 100, 100);

        jLabel2.setText("Arthur Bellato");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 220, 110, 16);

        jLabel3.setText("FAESA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 240, 70, 16);

        jLabel4.setText("Projeto Integrador");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 260, 110, 16);

        jLabel5.setText("Prof Lorena");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 276, 110, 20);

        jLabel6.setText("1º Número:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 30, 80, 16);

        jLabel7.setText("2º Número:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 30, 90, 16);

        jLabel8.setText("Selecione a operação abaixo:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 130, 190, 16);

        jLabel9.setText("Resultado:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 30, 90, 16);

        jLabel10.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CALCULADORA");
        jLabel10.setMaximumSize(new java.awt.Dimension(90, 30));
        jLabel10.setName(""); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 130, 100, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primeironumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeironumeroActionPerformed
 
        
    }//GEN-LAST:event_primeironumeroActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        
        int a, b;
        a = Integer.parseInt(primeironumero.getText());
        b = Integer.parseInt(segundonumero.getText());
        result.setText((a+b)+"");
        
                
        
        
        
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        
        int a, b;
        a = Integer.parseInt(primeironumero.getText());
        b = Integer.parseInt(segundonumero.getText());
        result.setText((a-b)+"");
        
        
        
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseReleased

        
        int a, b;
        a = Integer.parseInt(primeironumero.getText());
        b = Integer.parseInt(segundonumero.getText());
        result.setText((a*b)+"");
        
        
    }//GEN-LAST:event_jButton4MouseReleased

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
       int a, b;
        a = Integer.parseInt(primeironumero.getText());
        b = Integer.parseInt(segundonumero.getText());
        
        if (a==0 & b==0){
            result.setText("Indivisível");
        
        }else{
            result.setText((a/b)+"");
        }
    }//GEN-LAST:event_jButton3MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janelafrontal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janelafrontal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janelafrontal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janelafrontal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janelafrontal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField primeironumero;
    private javax.swing.JTextField result;
    private javax.swing.JTextField segundonumero;
    // End of variables declaration//GEN-END:variables
}
